### ISSUE TITLE
DocumentTranslationException

### ISSUE THREAD

**Issue by ay2456** [DeepLcom/deepl-python#19]
Hi there, I've been using the Deepl python package to translate the entire PDFs. I had it running for some time already and most of the time it worked perfectly. Today, I was going through the logs and found some failed cases and the error logs I've collected. I couldn't figure out what went wrong so please provide some suggestions on how to address them:

```
#1:
Traceback (most recent call last):
  File "/opt/document_translator.py", line 528, in translate_batch_docs
    target_lang=self.target_language_code)
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 780, in translate_document_from_filepath
    raise e
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 775, in translate_document_from_filepath
    glossary=glossary,
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 839, in translate_document
    "Error occurred while translating document", handle
deepl.exceptions.DocumentTranslationException: <super: <class 'DocumentTranslationException'>, <DocumentTranslationException object>>, document request: Document ID: B54E4E5999C915EF63AACA877843C03C, key: 2B17****
!
```

```
#2:
Traceback (most recent call last):
  File "/opt/document_translator.py", line 528, in translate_batch_docs
    target_lang=self.target_language_code)
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 780, in translate_document_from_filepath
    raise e
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 775, in translate_document_from_filepath
    glossary=glossary,
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 817, in translate_document
    glossary=glossary,
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 876, in translate_document_upload
    self._raise_for_status(status, content, json)
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 522, in _raise_for_status
    "Too many requests, DeepL servers are currently experiencing "
deepl.exceptions.TooManyRequestsException: Too many requests, DeepL servers are currently experiencing high load, message: Too many non-downloaded documents!
```

```
#3:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/conda/lib/python3.6/http/client.py", line 1379, in getresponse
    response.begin()
  File "/opt/conda/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/opt/conda/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/conda/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/conda/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/conda/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/opt/conda/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/lib/python3.6/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.deepl.com', port=443): Read timed out. (read timeout=10.886348485946655)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/deepl/http_client.py", line 168, in _internal_request
    request, stream=stream, timeout=timeout, **kwargs
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.deepl.com', port=443): Read timed out. (read timeout=10.886348485946655)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/document_translator.py", line 528, in translate_batch_docs
    target_lang=self.target_language_code)
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 780, in translate_document_from_filepath
    raise e
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 775, in translate_document_from_filepath
    glossary=glossary,
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 817, in translate_document
    glossary=glossary,
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 874, in translate_document_upload
    "v2/document", data=request_data, files=files
  File "/opt/conda/lib/python3.6/site-packages/deepl/translator.py", line 476, in _api_call
    **kwargs,
  File "/opt/conda/lib/python3.6/site-packages/deepl/http_client.py", line 119, in request_with_backoff
    raise exception
  File "/opt/conda/lib/python3.6/site-packages/deepl/http_client.py", line 106, in request_with_backoff
    request, stream=stream, timeout=backoff.get_timeout()
  File "/opt/conda/lib/python3.6/site-packages/deepl/http_client.py", line 184, in _internal_request
    raise ConnectionException(message, should_retry=True) from e
deepl.exceptions.ConnectionException: Request timed out: HTTPSConnectionPool(host='api.deepl.com', port=443): Read timed out. (read timeout=10.886348485946655)
!
```

I'm using `deepl==1.3.1` and the code I use was:
```
class DocumentTranslator(object):
    def __init__(self):
        self.translator = deepl.Translator(auth_key=AUTO_TRANSLATION_KEY)
        self.target_language_code = "en-us"

    def translate_batch_docs(pdfs):
        for pdf in pdfs:
            translated_pdf = pdf.replace('.pdf', '_translated.pdf')
            self.translator.translate_document_from_filepath(pdf, translated_pdf, target_lang=self.target_language_code)
```

**Comment by daniel-jones-deepl** [comment]
Hi @ay2456,
In # 2, it seems you have "Too many non-downloaded documents", so downloading some already-translated documents should resolve the issue.

In # 3, the request timed out. This was probably due to temporary problems with our network, so retrying that document.

In # 1, there was some error during translation on DeepL servers. Unfortunately due to a bug in the DocumentTranslationException stringize function, we cannot see in the log what the underlying cause was. That bug will be fixed soon.
However using the logged document ID and key you can try check the status and retrieve the document, using something like this:
```
def retrieve_document(id, key, output_path):
    handle = deepl.DocumentHandle(id, key)
    status = translator.translate_document_get_status(handle)
    if status.ok and status.done:
        translator.translate_document_download(handle, output_path)
        return True
    else:
        print("Document translation not finished or error occurred")
        return False
```

Your code seems fine, but you could consider catching any `DocumentTranslationException` and recording the `document_request` that contains the ID and key, so you can retrieve them later or contact support.

**Comment by daniel-jones-deepl** [comment]
[v1.4.1](https://github.com/DeepLcom/deepl-python/releases/tag/v1.4.1) includes the fix I described for # 1.

**Comment by ay2456** [comment]
@daniel-jones-deepl Thank you for the quick reply and fix! Appreciated it!

I have 2 follow-up questions:

Q1: Regarding the `retrieve_document` example you provided above, usually how long do I have to wait until I can consider the translation failed? Will it throw `DocumentTranslationException` as well?

Q2: In cases like # 1 where something failed on the Deepl server-side, am I getting billed for the request?

**Comment by ay2456** [comment]
@daniel-jones-deepl I updated the deepl package to 1.4.1 and ran into the # 1 exception again, this time the error log looked like this:

```
---------------------------------------------------------------------------
DocumentTranslationException              Traceback (most recent call last)
Input In [15], in <module>
----> 1 dt.translate_batch_docs([pdf_path])

Input In [12], in DocumentTranslator.translate_batch_docs(self, pdfs)
      7 for pdf in pdfs:
      8     translated_pdf = pdf.replace('.pdf', '_translated.pdf')
----> 9     self.translator.translate_document_from_filepath(pdf, translated_pdf, target_lang=self.target_language_code)

File /opt/conda/lib/python3.9/site-packages/deepl/translator.py:792, in Translator.translate_document_from_filepath(self, input_path, output_path, source_lang, target_lang, formality, glossary)
    790 out_file.close()
    791 os.unlink(output_path)
--> 792 raise e

File /opt/conda/lib/python3.9/site-packages/deepl/translator.py:781, in Translator.translate_document_from_filepath(self, input_path, output_path, source_lang, target_lang, formality, glossary)
    779 with open(output_path, "wb") as out_file:
    780     try:
--> 781         self.translate_document(
    782             in_file,
    783             out_file,
    784             target_lang=target_lang,
    785             source_lang=source_lang,
    786             formality=formality,
    787             glossary=glossary,
    788         )
    789     except Exception as e:
    790         out_file.close()

File /opt/conda/lib/python3.9/site-packages/deepl/translator.py:851, in Translator.translate_document(self, input_document, output_document, source_lang, target_lang, formality, glossary)
    848     raise DocumentTranslationException(str(e), handle) from e
    850 if not status.ok:
--> 851     raise DocumentTranslationException(
    852         "Error occurred while translating document", handle
    853     )

DocumentTranslationException: Error occurred while translating document, document request: Document ID: FEC7FDF4AAEEE98***, key: 50FEA198BA72CD7DADFA64F13***
```
It still doesn't say what was wrong.

Also, is there an easier way to fetch the `document_request`? I had to parse the error messages to get it right now?

**Comment by daniel-jones-deepl** [comment]
Hi @ay2456, sorry that this reply is so delayed.

Firstly your most recent question: yes, you can fetch the document request by catching the thrown exception, like this:

```
try:
    self.translator.translate...                       # Call deepl functions
except deepl.DocumentTranslationException as error:
    document_request = error.document_request          # Get the document_request
    document_id = document_request.document_id
    document_key = document_request.document_key
    ...                                                # Save the document ID and key for later use
    raise error                                        # Throw the error onwards
```

Just a quick extra note: `error.document_request` will soon be renamed to `error.document_handle` (to match the class `DocumentHandle`), but we'll make the change backward-compatible so the above code will still work.

Next, your earlier Q1: no, `Translator.translate_document_get_status` and `Translator.translate_document_download` do not throw `DocumentTranslationException`, and they should only throw if there is a connection error. A document translation error would be indicated in the status as `not status.ok`. In my experience, a document translation failure will be reported in seconds, but it could vary based on many factors. I can see now the retrieve_document example I gave above squashes the two cases of error and not-done together, we can split them apart to make it clearer:

```
def retrieve_document(id, key, output_path):
    handle = deepl.DocumentHandle(id, key)
    status = translator.translate_document_get_status(handle)
    if not status.ok:
        print("Document translation failed")  # Maybe you would prefer to raise an exception here?
        return False
    elif status.done:
        translator.translate_document_download(handle, output_path)
        return True
    else:
        print("Document translation not yet finished")
        return False
```

If your documents have a translation failure, you could contact our support.

Lastly, Q2: no we will not bill you if the document translation failure is on our side.

**Comment by daniel-jones-deepl** [comment]
Ah sorry, I also missed your point about the error message not saying what was wrong. Unfortunately our API does not expose an error message in case of document translation failure. So for that document could you please contact support?

**Comment by ay2456** [comment]
@daniel-jones-deepl Thank you for the reply! Let's do more testing. I'll close this issue if everything works properly.
